### PR TITLE
Development - Vishal - ProfileUser Creation and View

### PR DESCRIPTION
**Pull request by vishaldeepak**
-Created table that represents information about user.
-Made sure that whenever a new user is created corresponding row is generated with appropriate connections and empty value for all other fields, except admin which is set to false by default
- Using ProfileUser, we can now view and edit data of the corresponding columns
- Fixed the URL bug, by replacing 'action' with action_path

### CODE REVIEW

**Comment by nemelnikov** [comment]
Admin field is ok for now. But I think later we will delete it because of adding role based autorization.

**Comment by nemelnikov** [comment]
Do you plan to continue with ExpertProfile?

**Comment by vishaldeepak** [comment]
Expert Profile needs a bit of more thinking, on how we want to implement it

**Comment by nemelnikov** [comment]
If the Inuser is autentificated he is redirected to inuser's dashboard.
If the Expert is autentificated he is redirected to expert's dashboard.

That's all I think.

**Comment by nemelnikov** [comment]
Let's discuss it on Slack.

**Pull request merged**
